2025-03-31 18:12:16 [2025-03-31 11:12:16,352] INFO Initializing JDBC writer (io.confluent.connect.jdbc.sink.JdbcSinkTask)
2025-03-31 18:12:16 [2025-03-31 11:12:16,352] INFO Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects)
2025-03-31 18:12:16 [2025-03-31 11:12:16,352] INFO Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects)
2025-03-31 18:12:16 [2025-03-31 11:12:16,352] INFO Validating JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects)
2025-03-31 18:12:16 [2025-03-31 11:12:16,352] INFO Validated JDBC URL. (io.confluent.connect.jdbc.dialect.DatabaseDialects)
2025-03-31 18:12:16 [2025-03-31 11:12:16,352] INFO Initializing writer using SQL dialect: PostgreSqlDatabaseDialect (io.confluent.connect.jdbc.sink.JdbcSinkTask)
2025-03-31 18:12:16 [2025-03-31 11:12:16,352] INFO JDBC writer initialized (io.confluent.connect.jdbc.sink.JdbcSinkTask)
2025-03-31 18:12:16 [2025-03-31 11:12:16,352] ERROR WorkerSinkTask{id=postgres-sink-0} RetriableException from SinkTask: (org.apache.kafka.connect.runtime.WorkerSinkTask)
2025-03-31 18:12:16 org.apache.kafka.connect.errors.RetriableException: java.sql.SQLException: Exception chain:
2025-03-31 18:12:16 java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "blockchain_pg"."public"."eth_transactions" ("hash","blockHash","blockNumber","chainId","from","gas","gasPrice","input","maxFeePerGas","maxPriorityFeePerGas","nonce","r","s","to","transactionIndex","type","v","value","yParity") VALUES (('f75eafbb5c2d3be85631ad3b7c1b11356894caa4203f2e1b0840f69645e1ac36'),('73f7f0bbc612b84288717b0bc5d8a339f8f183260846410cd53f6ff4da156584'),('22166515'::int8),('1'::int8),('0xe581e1304641f69F038459e982C4fB35D99e3C05'),('232804'::int8),('491194017'::int8),('28f38d4e39d4380392994f50e2c8413ddffe7e720a7bf375ae401833e6ac236cc9dc8bb2984ba247255d747d49ff7469b5cea8d035ce'),('491194017'::int8),('0'::int8),('1525'::int8),('2cdd03d42fded09b69b9712f377ce46e61042bae47e27de6250859cec630396f'),('37b462f814b3ffb1a91c2d4813cabcd10f18be4b08404ea6549217773f7e571d'),('0x00F72Dde000091C62c51C600aF6F0000dd00562E'),('0'::int8),('2'::int4),('1'::int4),('7028424528781'::int8),('1'::int4)) ON CONFLICT ("hash") DO UPDATE SET "blockHash"=EXCLUDED."blockHash","blockNumber"=EXCLUDED."blockNumber","chainId"=EXCLUDED."chainId","from"=EXCLUDED."from","gas"=EXCLUDED."gas","gasPrice"=EXCLUDED."gasPrice","input"=EXCLUDED."input","maxFeePerGas"=EXCLUDED."maxFeePerGas","maxPriorityFeePerGas"=EXCLUDED."maxPriorityFeePerGas","nonce"=EXCLUDED."nonce","r"=EXCLUDED."r","s"=EXCLUDED."s","to"=EXCLUDED."to","transactionIndex"=EXCLUDED."transactionIndex","type"=EXCLUDED."type","v"=EXCLUDED."v","value"=EXCLUDED."value","yParity"=EXCLUDED."yParity" was aborted: ERROR: cannot execute INSERT in a read-only transaction  Call getNextException to see other errors in the batch.
2025-03-31 18:12:16 org.postgresql.util.PSQLException: ERROR: cannot execute INSERT in a read-only transaction
2025-03-31 18:12:16 org.postgresql.util.PSQLException: ERROR: cannot execute INSERT in a read-only transaction
2025-03-31 18:12:16 
2025-03-31 18:12:16     at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:119)
2025-03-31 18:12:16     at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
2025-03-31 18:12:16     at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
2025-03-31 18:12:16     at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
2025-03-31 18:12:16     at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
2025-03-31 18:12:16     at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
2025-03-31 18:12:16     at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
2025-03-31 18:12:16     at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
2025-03-31 18:12:16     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
2025-03-31 18:12:16     at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
2025-03-31 18:12:16     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2025-03-31 18:12:16     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2025-03-31 18:12:16     at java.base/java.lang.Thread.run(Unknown Source)
2025-03-31 18:12:16 Caused by: java.sql.SQLException: Exception chain:
2025-03-31 18:12:16 java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "blockchain_pg"."public"."eth_transactions" ("hash","blockHash","blockNumber","chainId","from","gas","gasPrice","input","maxFeePerGas","maxPriorityFeePerGas","nonce","r","s","to","transactionIndex","type","v","value","yParity") VALUES (('f75eafbb5c2d3be85631ad3b7c1b11356894caa4203f2e1b0840f69645e1ac36'),('73f7f0bbc612b84288717b0bc5d8a339f8f183260846410cd53f6ff4da156584'),('22166515'::int8),('1'::int8),('0xe581e1304641f69F038459e982C4fB35D99e3C05'),('232804'::int8),('491194017'::int8),('28f38d4e39d4380392994f50e2c8413ddffe7e720a7bf375ae401833e6ac236cc9dc8bb2984ba247255d747d49ff7469b5cea8d035ce'),('491194017'::int8),('0'::int8),('1525'::int8),('2cdd03d42fded09b69b9712f377ce46e61042bae47e27de6250859cec630396f'),('37b462f814b3ffb1a91c2d4813cabcd10f18be4b08404ea6549217773f7e571d'),('0x00F72Dde000091C62c51C600aF6F0000dd00562E'),('0'::int8),('2'::int4),('1'::int4),('7028424528781'::int8),('1'::int4)) ON CONFLICT ("hash") DO UPDATE SET "blockHash"=EXCLUDED."blockHash","blockNumber"=EXCLUDED."blockNumber","chainId"=EXCLUDED."chainId","from"=EXCLUDED."from","gas"=EXCLUDED."gas","gasPrice"=EXCLUDED."gasPrice","input"=EXCLUDED."input","maxFeePerGas"=EXCLUDED."maxFeePerGas","maxPriorityFeePerGas"=EXCLUDED."maxPriorityFeePerGas","nonce"=EXCLUDED."nonce","r"=EXCLUDED."r","s"=EXCLUDED."s","to"=EXCLUDED."to","transactionIndex"=EXCLUDED."transactionIndex","type"=EXCLUDED."type","v"=EXCLUDED."v","value"=EXCLUDED."value","yParity"=EXCLUDED."yParity" was aborted: ERROR: cannot execute INSERT in a read-only transaction  Call getNextException to see other errors in the batch.
2025-03-31 18:12:16 org.postgresql.util.PSQLException: ERROR: cannot execute INSERT in a read-only transaction
2025-03-31 18:12:16 org.postgresql.util.PSQLException: ERROR: cannot execute INSERT in a read-only transaction
2025-03-31 18:12:16 
2025-03-31 18:12:16     at io.confluent.connect.jdbc.sink.JdbcSinkTask.getAllMessagesException(JdbcSinkTask.java:167)
2025-03-31 18:12:16     at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:112)
2025-03-31 18:12:16     ... 12 more
2025-03-31 18:12:21 [2025-03-31 11:12:21,077] INFO Maximum table name length for database is 63 bytes (io.confluent.connect.jdbc.dialect.PostgreSqlDatabaseDialect)
2025-03-31 18:12:21 [2025-03-31 11:12:21,077] INFO JdbcDbWriter Connected (io.confluent.connect.jdbc.sink.JdbcDbWriter)
2025-03-31 18:12:21 [2025-03-31 11:12:21,077] INFO Database connection established. (io.confluent.connect.jdbc.util.CachedConnectionProvider)
2025-03-31 18:12:22 [2025-03-31 11:12:22,850] INFO Checking PostgreSql dialect for existence of TABLE "blockchain_pg"."public"."eth_transactions" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect)
2025-03-31 18:12:23 [2025-03-31 11:12:23,064] INFO Using PostgreSql dialect TABLE "blockchain_pg"."public"."eth_transactions" present (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect)
2025-03-31 18:12:23 [2025-03-31 11:12:23,501] INFO Checking PostgreSql dialect for type of TABLE "blockchain_pg"."public"."eth_transactions" (io.confluent.connect.jdbc.dialect.GenericDatabaseDialect)
2025-03-31 18:12:24 [2025-03-31 11:12:24,117] INFO Setting metadata for table "blockchain_pg"."public"."eth_transactions" to Table{name='"blockchain_pg"."public"."eth_transactions"', type=TABLE columns=[Column{'hash', isPrimaryKey=true, allowsNull=false, sqlType=varchar}, Column{'blockHash', isPrimaryKey=false, allowsNull=true, sqlType=varchar}, Column{'from', isPrimaryKey=false, allowsNull=true, sqlType=varchar}, Column{'to', isPrimaryKey=false, allowsNull=true, sqlType=varchar}, Column{'yParity', isPrimaryKey=false, allowsNull=true, sqlType=int4}, Column{'v', isPrimaryKey=false, allowsNull=true, sqlType=int4}, Column{'blockNumber', isPrimaryKey=false, allowsNull=true, sqlType=int4}, Column{'transactionIndex', isPrimaryKey=false, allowsNull=true, sqlType=int4}, Column{'r', isPrimaryKey=false, allowsNull=true, sqlType=varchar}, Column{'s', isPrimaryKey=false, allowsNull=true, sqlType=varchar}, Column{'type', isPrimaryKey=false, allowsNull=true, sqlType=int8}, Column{'nonce', isPrimaryKey=false, allowsNull=true, sqlType=varchar}, Column{'timestamp', isPrimaryKey=false, allowsNull=true, sqlType=date}, Column{'input', isPrimaryKey=false, allowsNull=true, sqlType=text}, Column{'maxPriorityFeePerGas', isPrimaryKey=false, allowsNull=true, sqlType=int8}, Column{'gas', isPrimaryKey=false, allowsNull=true, sqlType=int4}, Column{'value', isPrimaryKey=false, allowsNull=true, sqlType=int8}, Column{'chainId', isPrimaryKey=false, allowsNull=true, sqlType=varchar}, Column{'gasPrice', isPrimaryKey=false, allowsNull=true, sqlType=int8}, Column{'maxFeePerGas', isPrimaryKey=false, allowsNull=true, sqlType=int8}]} (io.confluent.connect.jdbc.util.TableDefinitions)
2025-03-31 18:12:24 [2025-03-31 11:12:24,403] ERROR Error during write operation. Attempting rollback. (io.confluent.connect.jdbc.sink.JdbcDbWriter)
2025-03-31 18:12:24 java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "blockchain_pg"."public"."eth_transactions" ("hash","blockHash","blockNumber","chainId","from","gas","gasPrice","input","maxFeePerGas","maxPriorityFeePerGas","nonce","r","s","to","transactionIndex","type","v","value","yParity") VALUES (('f75eafbb5c2d3be85631ad3b7c1b11356894caa4203f2e1b0840f69645e1ac36'),('73f7f0bbc612b84288717b0bc5d8a339f8f183260846410cd53f6ff4da156584'),('22166515'::int8),('1'::int8),('0xe581e1304641f69F038459e982C4fB35D99e3C05'),('232804'::int8),('491194017'::int8),('28f38d4e39d4380392994f50e2c8413ddffe7e720a7bf375ae401833e6ac236cc9dc8bb2984ba247255d747d49ff7469b5cea8d035ce'),('491194017'::int8),('0'::int8),('1525'::int8),('2cdd03d42fded09b69b9712f377ce46e61042bae47e27de6250859cec630396f'),('37b462f814b3ffb1a91c2d4813cabcd10f18be4b08404ea6549217773f7e571d'),('0x00F72Dde000091C62c51C600aF6F0000dd00562E'),('0'::int8),('2'::int4),('1'::int4),('7028424528781'::int8),('1'::int4)) ON CONFLICT ("hash") DO UPDATE SET "blockHash"=EXCLUDED."blockHash","blockNumber"=EXCLUDED."blockNumber","chainId"=EXCLUDED."chainId","from"=EXCLUDED."from","gas"=EXCLUDED."gas","gasPrice"=EXCLUDED."gasPrice","input"=EXCLUDED."input","maxFeePerGas"=EXCLUDED."maxFeePerGas","maxPriorityFeePerGas"=EXCLUDED."maxPriorityFeePerGas","nonce"=EXCLUDED."nonce","r"=EXCLUDED."r","s"=EXCLUDED."s","to"=EXCLUDED."to","transactionIndex"=EXCLUDED."transactionIndex","type"=EXCLUDED."type","v"=EXCLUDED."v","value"=EXCLUDED."value","yParity"=EXCLUDED."yParity" was aborted: ERROR: cannot execute INSERT in a read-only transaction  Call getNextException to see other errors in the batch.
2025-03-31 18:12:24     at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
2025-03-31 18:12:24     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2367)
2025-03-31 18:12:24     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:560)
2025-03-31 18:12:24     at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:893)
2025-03-31 18:12:24     at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:916)
2025-03-31 18:12:24     at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1684)
2025-03-31 18:12:24     at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
2025-03-31 18:12:24     at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
2025-03-31 18:12:24     at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:83)
2025-03-31 18:12:24     at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
2025-03-31 18:12:24     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
2025-03-31 18:12:24     at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
2025-03-31 18:12:24     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2025-03-31 18:12:24     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2025-03-31 18:12:24     at java.base/java.lang.Thread.run(Unknown Source)
2025-03-31 18:12:24 Caused by: org.postgresql.util.PSQLException: ERROR: cannot execute INSERT in a read-only transaction
2025-03-31 18:12:24     at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
2025-03-31 18:12:24     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
2025-03-31 18:12:24     ... 20 more
2025-03-31 18:12:24 [2025-03-31 11:12:24,686] INFO Successfully rolled back transaction (io.confluent.connect.jdbc.sink.JdbcDbWriter)
2025-03-31 18:12:24 [2025-03-31 11:12:24,686] WARN Write of 1 records failed, remainingRetries=0 (io.confluent.connect.jdbc.sink.JdbcSinkTask)
2025-03-31 18:12:24 java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "blockchain_pg"."public"."eth_transactions" ("hash","blockHash","blockNumber","chainId","from","gas","gasPrice","input","maxFeePerGas","maxPriorityFeePerGas","nonce","r","s","to","transactionIndex","type","v","value","yParity") VALUES (('f75eafbb5c2d3be85631ad3b7c1b11356894caa4203f2e1b0840f69645e1ac36'),('73f7f0bbc612b84288717b0bc5d8a339f8f183260846410cd53f6ff4da156584'),('22166515'::int8),('1'::int8),('0xe581e1304641f69F038459e982C4fB35D99e3C05'),('232804'::int8),('491194017'::int8),('28f38d4e39d4380392994f50e2c8413ddffe7e720a7bf375ae401833e6ac236cc9dc8bb2984ba247255d747d49ff7469b5cea8d035ce'),('491194017'::int8),('0'::int8),('1525'::int8),('2cdd03d42fded09b69b9712f377ce46e61042bae47e27de6250859cec630396f'),('37b462f814b3ffb1a91c2d4813cabcd10f18be4b08404ea6549217773f7e571d'),('0x00F72Dde000091C62c51C600aF6F0000dd00562E'),('0'::int8),('2'::int4),('1'::int4),('7028424528781'::int8),('1'::int4)) ON CONFLICT ("hash") DO UPDATE SET "blockHash"=EXCLUDED."blockHash","blockNumber"=EXCLUDED."blockNumber","chainId"=EXCLUDED."chainId","from"=EXCLUDED."from","gas"=EXCLUDED."gas","gasPrice"=EXCLUDED."gasPrice","input"=EXCLUDED."input","maxFeePerGas"=EXCLUDED."maxFeePerGas","maxPriorityFeePerGas"=EXCLUDED."maxPriorityFeePerGas","nonce"=EXCLUDED."nonce","r"=EXCLUDED."r","s"=EXCLUDED."s","to"=EXCLUDED."to","transactionIndex"=EXCLUDED."transactionIndex","type"=EXCLUDED."type","v"=EXCLUDED."v","value"=EXCLUDED."value","yParity"=EXCLUDED."yParity" was aborted: ERROR: cannot execute INSERT in a read-only transaction  Call getNextException to see other errors in the batch.
2025-03-31 18:12:24     at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
2025-03-31 18:12:24     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2367)
2025-03-31 18:12:24     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:560)
2025-03-31 18:12:24     at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:893)
2025-03-31 18:12:24     at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:916)
2025-03-31 18:12:24     at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1684)
2025-03-31 18:12:24     at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:198)
2025-03-31 18:12:24     at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:188)
2025-03-31 18:12:24     at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:83)
2025-03-31 18:12:24     at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:90)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
2025-03-31 18:12:24     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
2025-03-31 18:12:24     at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
2025-03-31 18:12:24     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2025-03-31 18:12:24     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2025-03-31 18:12:24     at java.base/java.lang.Thread.run(Unknown Source)
2025-03-31 18:12:24 Caused by: org.postgresql.util.PSQLException: ERROR: cannot execute INSERT in a read-only transaction
2025-03-31 18:12:24     at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
2025-03-31 18:12:24     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
2025-03-31 18:12:24     ... 20 more
2025-03-31 18:12:24 [2025-03-31 11:12:24,686] ERROR Failing task after exhausting retries; encountered 3 exceptions on last write attempt. For complete details on each exception, please enable DEBUG logging. (io.confluent.connect.jdbc.sink.JdbcSinkTask)
2025-03-31 18:12:24 [2025-03-31 11:12:24,687] ERROR WorkerSinkTask{id=postgres-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: java.sql.SQLException: Exception chain:
2025-03-31 18:12:24 java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "blockchain_pg"."public"."eth_transactions" ("hash","blockHash","blockNumber","chainId","from","gas","gasPrice","input","maxFeePerGas","maxPriorityFeePerGas","nonce","r","s","to","transactionIndex","type","v","value","yParity") VALUES (('f75eafbb5c2d3be85631ad3b7c1b11356894caa4203f2e1b0840f69645e1ac36'),('73f7f0bbc612b84288717b0bc5d8a339f8f183260846410cd53f6ff4da156584'),('22166515'::int8),('1'::int8),('0xe581e1304641f69F038459e982C4fB35D99e3C05'),('232804'::int8),('491194017'::int8),('28f38d4e39d4380392994f50e2c8413ddffe7e720a7bf375ae401833e6ac236cc9dc8bb2984ba247255d747d49ff7469b5cea8d035ce'),('491194017'::int8),('0'::int8),('1525'::int8),('2cdd03d42fded09b69b9712f377ce46e61042bae47e27de6250859cec630396f'),('37b462f814b3ffb1a91c2d4813cabcd10f18be4b08404ea6549217773f7e571d'),('0x00F72Dde000091C62c51C600aF6F0000dd00562E'),('0'::int8),('2'::int4),('1'::int4),('7028424528781'::int8),('1'::int4)) ON CONFLICT ("hash") DO UPDATE SET "blockHash"=EXCLUDED."blockHash","blockNumber"=EXCLUDED."blockNumber","chainId"=EXCLUDED."chainId","from"=EXCLUDED."from","gas"=EXCLUDED."gas","gasPrice"=EXCLUDED."gasPrice","input"=EXCLUDED."input","maxFeePerGas"=EXCLUDED."maxFeePerGas","maxPriorityFeePerGas"=EXCLUDED."maxPriorityFeePerGas","nonce"=EXCLUDED."nonce","r"=EXCLUDED."r","s"=EXCLUDED."s","to"=EXCLUDED."to","transactionIndex"=EXCLUDED."transactionIndex","type"=EXCLUDED."type","v"=EXCLUDED."v","value"=EXCLUDED."value","yParity"=EXCLUDED."yParity" was aborted: ERROR: cannot execute INSERT in a read-only transaction  Call getNextException to see other errors in the batch.
2025-03-31 18:12:24 org.postgresql.util.PSQLException: ERROR: cannot execute INSERT in a read-only transaction
2025-03-31 18:12:24 org.postgresql.util.PSQLException: ERROR: cannot execute INSERT in a read-only transaction
2025-03-31 18:12:24  (org.apache.kafka.connect.runtime.WorkerSinkTask)
2025-03-31 18:12:24 org.apache.kafka.connect.errors.ConnectException: java.sql.SQLException: Exception chain:
2025-03-31 18:12:24 java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "blockchain_pg"."public"."eth_transactions" ("hash","blockHash","blockNumber","chainId","from","gas","gasPrice","input","maxFeePerGas","maxPriorityFeePerGas","nonce","r","s","to","transactionIndex","type","v","value","yParity") VALUES (('f75eafbb5c2d3be85631ad3b7c1b11356894caa4203f2e1b0840f69645e1ac36'),('73f7f0bbc612b84288717b0bc5d8a339f8f183260846410cd53f6ff4da156584'),('22166515'::int8),('1'::int8),('0xe581e1304641f69F038459e982C4fB35D99e3C05'),('232804'::int8),('491194017'::int8),('28f38d4e39d4380392994f50e2c8413ddffe7e720a7bf375ae401833e6ac236cc9dc8bb2984ba247255d747d49ff7469b5cea8d035ce'),('491194017'::int8),('0'::int8),('1525'::int8),('2cdd03d42fded09b69b9712f377ce46e61042bae47e27de6250859cec630396f'),('37b462f814b3ffb1a91c2d4813cabcd10f18be4b08404ea6549217773f7e571d'),('0x00F72Dde000091C62c51C600aF6F0000dd00562E'),('0'::int8),('2'::int4),('1'::int4),('7028424528781'::int8),('1'::int4)) ON CONFLICT ("hash") DO UPDATE SET "blockHash"=EXCLUDED."blockHash","blockNumber"=EXCLUDED."blockNumber","chainId"=EXCLUDED."chainId","from"=EXCLUDED."from","gas"=EXCLUDED."gas","gasPrice"=EXCLUDED."gasPrice","input"=EXCLUDED."input","maxFeePerGas"=EXCLUDED."maxFeePerGas","maxPriorityFeePerGas"=EXCLUDED."maxPriorityFeePerGas","nonce"=EXCLUDED."nonce","r"=EXCLUDED."r","s"=EXCLUDED."s","to"=EXCLUDED."to","transactionIndex"=EXCLUDED."transactionIndex","type"=EXCLUDED."type","v"=EXCLUDED."v","value"=EXCLUDED."value","yParity"=EXCLUDED."yParity" was aborted: ERROR: cannot execute INSERT in a read-only transaction  Call getNextException to see other errors in the batch.
2025-03-31 18:12:24 org.postgresql.util.PSQLException: ERROR: cannot execute INSERT in a read-only transaction
2025-03-31 18:12:24 org.postgresql.util.PSQLException: ERROR: cannot execute INSERT in a read-only transaction
2025-03-31 18:12:24 
2025-03-31 18:12:24     at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:133)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
2025-03-31 18:12:24     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
2025-03-31 18:12:24     at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
2025-03-31 18:12:24     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2025-03-31 18:12:24     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2025-03-31 18:12:24     at java.base/java.lang.Thread.run(Unknown Source)
2025-03-31 18:12:24 Caused by: java.sql.SQLException: Exception chain:
2025-03-31 18:12:24 java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "blockchain_pg"."public"."eth_transactions" ("hash","blockHash","blockNumber","chainId","from","gas","gasPrice","input","maxFeePerGas","maxPriorityFeePerGas","nonce","r","s","to","transactionIndex","type","v","value","yParity") VALUES (('f75eafbb5c2d3be85631ad3b7c1b11356894caa4203f2e1b0840f69645e1ac36'),('73f7f0bbc612b84288717b0bc5d8a339f8f183260846410cd53f6ff4da156584'),('22166515'::int8),('1'::int8),('0xe581e1304641f69F038459e982C4fB35D99e3C05'),('232804'::int8),('491194017'::int8),('28f38d4e39d4380392994f50e2c8413ddffe7e720a7bf375ae401833e6ac236cc9dc8bb2984ba247255d747d49ff7469b5cea8d035ce'),('491194017'::int8),('0'::int8),('1525'::int8),('2cdd03d42fded09b69b9712f377ce46e61042bae47e27de6250859cec630396f'),('37b462f814b3ffb1a91c2d4813cabcd10f18be4b08404ea6549217773f7e571d'),('0x00F72Dde000091C62c51C600aF6F0000dd00562E'),('0'::int8),('2'::int4),('1'::int4),('7028424528781'::int8),('1'::int4)) ON CONFLICT ("hash") DO UPDATE SET "blockHash"=EXCLUDED."blockHash","blockNumber"=EXCLUDED."blockNumber","chainId"=EXCLUDED."chainId","from"=EXCLUDED."from","gas"=EXCLUDED."gas","gasPrice"=EXCLUDED."gasPrice","input"=EXCLUDED."input","maxFeePerGas"=EXCLUDED."maxFeePerGas","maxPriorityFeePerGas"=EXCLUDED."maxPriorityFeePerGas","nonce"=EXCLUDED."nonce","r"=EXCLUDED."r","s"=EXCLUDED."s","to"=EXCLUDED."to","transactionIndex"=EXCLUDED."transactionIndex","type"=EXCLUDED."type","v"=EXCLUDED."v","value"=EXCLUDED."value","yParity"=EXCLUDED."yParity" was aborted: ERROR: cannot execute INSERT in a read-only transaction  Call getNextException to see other errors in the batch.
2025-03-31 18:12:24 org.postgresql.util.PSQLException: ERROR: cannot execute INSERT in a read-only transaction
2025-03-31 18:12:24 org.postgresql.util.PSQLException: ERROR: cannot execute INSERT in a read-only transaction
2025-03-31 18:12:24 
2025-03-31 18:12:24     at io.confluent.connect.jdbc.sink.JdbcSinkTask.getAllMessagesException(JdbcSinkTask.java:167)
2025-03-31 18:12:24     at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:112)
2025-03-31 18:12:24     ... 12 more
2025-03-31 18:12:24 [2025-03-31 11:12:24,687] ERROR WorkerSinkTask{id=postgres-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
2025-03-31 18:12:24 org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:635)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:344)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:246)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:215)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:225)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
2025-03-31 18:12:24     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
2025-03-31 18:12:24     at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
2025-03-31 18:12:24     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2025-03-31 18:12:24     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2025-03-31 18:12:24     at java.base/java.lang.Thread.run(Unknown Source)
2025-03-31 18:12:24 Caused by: org.apache.kafka.connect.errors.ConnectException: java.sql.SQLException: Exception chain:
2025-03-31 18:12:24 java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "blockchain_pg"."public"."eth_transactions" ("hash","blockHash","blockNumber","chainId","from","gas","gasPrice","input","maxFeePerGas","maxPriorityFeePerGas","nonce","r","s","to","transactionIndex","type","v","value","yParity") VALUES (('f75eafbb5c2d3be85631ad3b7c1b11356894caa4203f2e1b0840f69645e1ac36'),('73f7f0bbc612b84288717b0bc5d8a339f8f183260846410cd53f6ff4da156584'),('22166515'::int8),('1'::int8),('0xe581e1304641f69F038459e982C4fB35D99e3C05'),('232804'::int8),('491194017'::int8),('28f38d4e39d4380392994f50e2c8413ddffe7e720a7bf375ae401833e6ac236cc9dc8bb2984ba247255d747d49ff7469b5cea8d035ce'),('491194017'::int8),('0'::int8),('1525'::int8),('2cdd03d42fded09b69b9712f377ce46e61042bae47e27de6250859cec630396f'),('37b462f814b3ffb1a91c2d4813cabcd10f18be4b08404ea6549217773f7e571d'),('0x00F72Dde000091C62c51C600aF6F0000dd00562E'),('0'::int8),('2'::int4),('1'::int4),('7028424528781'::int8),('1'::int4)) ON CONFLICT ("hash") DO UPDATE SET "blockHash"=EXCLUDED."blockHash","blockNumber"=EXCLUDED."blockNumber","chainId"=EXCLUDED."chainId","from"=EXCLUDED."from","gas"=EXCLUDED."gas","gasPrice"=EXCLUDED."gasPrice","input"=EXCLUDED."input","maxFeePerGas"=EXCLUDED."maxFeePerGas","maxPriorityFeePerGas"=EXCLUDED."maxPriorityFeePerGas","nonce"=EXCLUDED."nonce","r"=EXCLUDED."r","s"=EXCLUDED."s","to"=EXCLUDED."to","transactionIndex"=EXCLUDED."transactionIndex","type"=EXCLUDED."type","v"=EXCLUDED."v","value"=EXCLUDED."value","yParity"=EXCLUDED."yParity" was aborted: ERROR: cannot execute INSERT in a read-only transaction  Call getNextException to see other errors in the batch.
2025-03-31 18:12:24 org.postgresql.util.PSQLException: ERROR: cannot execute INSERT in a read-only transaction
2025-03-31 18:12:24 org.postgresql.util.PSQLException: ERROR: cannot execute INSERT in a read-only transaction
2025-03-31 18:12:24 
2025-03-31 18:12:24     at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:133)
2025-03-31 18:12:24     at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:605)
2025-03-31 18:12:24     ... 11 more
2025-03-31 18:12:24 Caused by: java.sql.SQLException: Exception chain:
2025-03-31 18:12:24 java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "blockchain_pg"."public"."eth_transactions" ("hash","blockHash","blockNumber","chainId","from","gas","gasPrice","input","maxFeePerGas","maxPriorityFeePerGas","nonce","r","s","to","transactionIndex","type","v","value","yParity") VALUES (('f75eafbb5c2d3be85631ad3b7c1b11356894caa4203f2e1b0840f69645e1ac36'),('73f7f0bbc612b84288717b0bc5d8a339f8f183260846410cd53f6ff4da156584'),('22166515'::int8),('1'::int8),('0xe581e1304641f69F038459e982C4fB35D99e3C05'),('232804'::int8),('491194017'::int8),('28f38d4e39d4380392994f50e2c8413ddffe7e720a7bf375ae401833e6ac236cc9dc8bb2984ba247255d747d49ff7469b5cea8d035ce'),('491194017'::int8),('0'::int8),('1525'::int8),('2cdd03d42fded09b69b9712f377ce46e61042bae47e27de6250859cec630396f'),('37b462f814b3ffb1a91c2d4813cabcd10f18be4b08404ea6549217773f7e571d'),('0x00F72Dde000091C62c51C600aF6F0000dd00562E'),('0'::int8),('2'::int4),('1'::int4),('7028424528781'::int8),('1'::int4)) ON CONFLICT ("hash") DO UPDATE SET "blockHash"=EXCLUDED."blockHash","blockNumber"=EXCLUDED."blockNumber","chainId"=EXCLUDED."chainId","from"=EXCLUDED."from","gas"=EXCLUDED."gas","gasPrice"=EXCLUDED."gasPrice","input"=EXCLUDED."input","maxFeePerGas"=EXCLUDED."maxFeePerGas","maxPriorityFeePerGas"=EXCLUDED."maxPriorityFeePerGas","nonce"=EXCLUDED."nonce","r"=EXCLUDED."r","s"=EXCLUDED."s","to"=EXCLUDED."to","transactionIndex"=EXCLUDED."transactionIndex","type"=EXCLUDED."type","v"=EXCLUDED."v","value"=EXCLUDED."value","yParity"=EXCLUDED."yParity" was aborted: ERROR: cannot execute INSERT in a read-only transaction  Call getNextException to see other errors in the batch.
2025-03-31 18:12:24 org.postgresql.util.PSQLException: ERROR: cannot execute INSERT in a read-only transaction
2025-03-31 18:12:24 org.postgresql.util.PSQLException: ERROR: cannot execute INSERT in a read-only transaction
2025-03-31 18:12:24 
2025-03-31 18:12:24     at io.confluent.connect.jdbc.sink.JdbcSinkTask.getAllMessagesException(JdbcSinkTask.java:167)
2025-03-31 18:12:24     at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:112)
2025-03-31 18:12:24     ... 12 more
2025-03-31 18:12:24 [2025-03-31 11:12:24,687] INFO Stopping task (io.confluent.connect.jdbc.sink.JdbcSinkTask)
2025-03-31 18:12:24 [2025-03-31 11:12:24,690] INFO [Consumer clientId=connector-consumer-postgres-sink-0, groupId=connect-postgres-sink] Revoke previously assigned partitions ethereum-0 (org.apache.kafka.clients.consumer.internals.ConsumerRebalanceListenerInvoker)
2025-03-31 18:12:24 [2025-03-31 11:12:24,690] INFO [Consumer clientId=connector-consumer-postgres-sink-0, groupId=connect-postgres-sink] The pause flag in partitions [ethereum-0] will be removed due to revocation. (org.apache.kafka.clients.consumer.internals.ConsumerRebalanceListenerInvoker)
2025-03-31 18:12:24 [2025-03-31 11:12:24,690] INFO [Consumer clientId=connector-consumer-postgres-sink-0, groupId=connect-postgres-sink] Member connector-consumer-postgres-sink-0-cb0714f8-e23a-41e0-a9ed-4221e8d35ea2 sending LeaveGroup request to coordinator 172.28.0.10:9092 (id: 2147483647 rack: null) due to the consumer is being closed (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
2025-03-31 18:12:24 [2025-03-31 11:12:24,691] INFO [Consumer clientId=connector-consumer-postgres-sink-0, groupId=connect-postgres-sink] Resetting generation and member id due to: consumer pro-actively leaving the group (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
2025-03-31 18:12:24 [2025-03-31 11:12:24,691] INFO [Consumer clientId=connector-consumer-postgres-sink-0, groupId=connect-postgres-sink] Request joining group due to: consumer pro-actively leaving the group (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
2025-03-31 18:12:24 [2025-03-31 11:12:24,696] INFO Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics)
2025-03-31 18:12:24 [2025-03-31 11:12:24,696] INFO Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics)
2025-03-31 18:12:24 [2025-03-31 11:12:24,696] INFO Closing reporter org.apache.kafka.common.telemetry.internals.ClientTelemetryReporter (org.apache.kafka.common.metrics.Metrics)
2025-03-31 18:12:24 [2025-03-31 11:12:24,696] INFO Metrics reporters closed (org.apache.kafka.common.metrics.Metrics)
2025-03-31 18:12:24 [2025-03-31 11:12:24,698] INFO App info kafka.consumer for connector-consumer-postgres-sink-0 unregistered (org.apache.kafka.common.utils.AppInfoParser)
2025-03-31 18:16:11 [2025-03-31 11:16:11,107] INFO [AdminClient clientId=connect-shared-admin] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient)