[2025-04-07T08:31:55.237+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: RSS.init.set_connections manual__2025-04-07T08:10:53.749896+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
