[2025-04-07T08:05:01.770+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: RSS.init.set_connections scheduled__2025-01-03T00:01:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
