[2025-04-09T08:21:46.796+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-09T08:21:46.810+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Telegram.get_posts manual__2025-04-09T08:21:33.701005+00:00 [queued]>
[2025-04-09T08:21:46.815+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Telegram.get_posts manual__2025-04-09T08:21:33.701005+00:00 [queued]>
[2025-04-09T08:21:46.816+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-09T08:21:46.826+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_posts> on 2025-04-09 08:21:33.701005+00:00
[2025-04-09T08:21:46.837+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=97) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-09T08:21:46.838+0000] {standard_task_runner.py:63} INFO - Started process 99 to run task
[2025-04-09T08:21:46.839+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Telegram', 'get_posts', 'manual__2025-04-09T08:21:33.701005+00:00', '--job-id', '223', '--raw', '--subdir', 'DAGS_FOLDER/TG_MSG_DAG.py', '--cfg-path', '/tmp/tmp81w9zmik']
[2025-04-09T08:21:46.841+0000] {standard_task_runner.py:91} INFO - Job 223: Subtask get_posts
[2025-04-09T08:21:46.873+0000] {task_command.py:426} INFO - Running <TaskInstance: Telegram.get_posts manual__2025-04-09T08:21:33.701005+00:00 [running]> on host fc960ba5f8ab
[2025-04-09T08:21:46.931+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='user' AIRFLOW_CTX_DAG_ID='Telegram' AIRFLOW_CTX_TASK_ID='get_posts' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T08:21:33.701005+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T08:21:33.701005+00:00'
[2025-04-09T08:21:46.932+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-09T08:21:46.941+0000] {TG_MSG_DAG.py:35} INFO - Starting Telegram posts collection
[2025-04-09T08:21:47.064+0000] {mtprotosender.py:228} INFO - Connecting to 149.154.167.51:443/TcpFull...
[2025-04-09T08:21:48.787+0000] {mtprotosender.py:279} INFO - Connection to 149.154.167.51:443/TcpFull complete!
[2025-04-09T08:21:49.592+0000] {logging_mixin.py:188} INFO - Please enter your phone (or bot token): 
[2025-04-09T08:21:49.593+0000] {TG_MSG_DAG.py:94} ERROR - Telegram API connection error: EOF when reading a line (Type: EOFError)
[2025-04-09T08:21:49.593+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-09T08:21:49.594+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/TG_MSG_DAG.py", line 37, in get_posts
    with TelegramClient('Get_msg', api_id, api_hash) as tg_client:
  File "/home/airflow/.local/lib/python3.12/site-packages/telethon/helpers.py", line 219, in _sync_enter
    return loop.run_until_complete(self.__aenter__())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/telethon/client/auth.py", line 657, in __aenter__
    return await self.start()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/telethon/client/auth.py", line 165, in _start
    value = phone()
            ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/telethon/client/auth.py", line 22, in <lambda>
    phone: typing.Union[typing.Callable[[], str], str] = lambda: input('Please enter your phone (or bot token): '),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: EOF when reading a line
[2025-04-09T08:21:49.603+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Telegram, task_id=get_posts, run_id=manual__2025-04-09T08:21:33.701005+00:00, execution_date=20250409T082133, start_date=20250409T082146, end_date=20250409T082149
[2025-04-09T08:21:49.616+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 223 for task get_posts (EOF when reading a line; 99)
[2025-04-09T08:21:49.658+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-09T08:21:49.674+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-09T08:21:49.679+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
