[2025-04-07T10:28:38.211+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-07T10:28:38.228+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: RSS.process_news manual__2025-04-07T10:28:28.308556+00:00 [queued]>
[2025-04-07T10:28:38.234+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: RSS.process_news manual__2025-04-07T10:28:28.308556+00:00 [queued]>
[2025-04-07T10:28:38.235+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-07T10:28:38.247+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_news> on 2025-04-07 10:28:28.308556+00:00
[2025-04-07T10:28:38.255+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=93) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-07T10:28:38.256+0000] {standard_task_runner.py:63} INFO - Started process 94 to run task
[2025-04-07T10:28:38.256+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'RSS', 'process_news', 'manual__2025-04-07T10:28:28.308556+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/RSS_DAG.py', '--cfg-path', '/tmp/tmpt0tqh0vt']
[2025-04-07T10:28:38.257+0000] {standard_task_runner.py:91} INFO - Job 129: Subtask process_news
[2025-04-07T10:28:38.294+0000] {task_command.py:426} INFO - Running <TaskInstance: RSS.process_news manual__2025-04-07T10:28:28.308556+00:00 [running]> on host 30d2f34b5b81
[2025-04-07T10:28:38.360+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='user' AIRFLOW_CTX_DAG_ID='RSS' AIRFLOW_CTX_TASK_ID='process_news' AIRFLOW_CTX_EXECUTION_DATE='2025-04-07T10:28:28.308556+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-07T10:28:28.308556+00:00'
[2025-04-07T10:28:38.361+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-07T10:28:38.375+0000] {base.py:84} INFO - Using connection ID 'mongo_conn' for task execution.
[2025-04-07T10:28:38.376+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-07T10:28:38.382+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/RSS_DAG.py", line 73, in process_news
    mongo_hook = MongoHook(mongo_conn_id='mongo_conn')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mongo/hooks/mongo.py", line 123, in __init__
    self._validate_connection(conn)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mongo/hooks/mongo.py", line 159, in _validate_connection
    raise AirflowConfigException(
airflow.exceptions.AirflowConfigException: conn_type 'MongoDB' not allowed for MongoHook; conn_type must be 'mongo'
[2025-04-07T10:28:38.389+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=RSS, task_id=process_news, run_id=manual__2025-04-07T10:28:28.308556+00:00, execution_date=20250407T102828, start_date=20250407T102838, end_date=20250407T102838
[2025-04-07T10:28:38.401+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 129 for task process_news (conn_type 'MongoDB' not allowed for MongoHook; conn_type must be 'mongo'; 94)
[2025-04-07T10:28:38.430+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-07T10:28:38.446+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-07T10:28:38.451+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
